Repository BIT-Studio-3/Space-Rescue, pull requests merged in 2023-09, with the labels that each got.

#183 Remove exclamation points from end game messages
  Assets/Scripts/Managers/GameEndManager.cs
Labels: bug

#181 Create LICENSE
  LICENSE
  README.md
Labels: documentation

#185 Fixing Button Text in Menu's
  Assets/Scenes/Game End.unity
  Assets/Scenes/Main scene.unity
  Assets/Scenes/Planet.unity
  Assets/Scenes/Title Screen.unity
Labels: Visuals

#189 CI Reducing Build Time
  .github/workflows/ci-build-and-release.yml
  .github/workflows/ci-schedule-cache.yml
Labels: Continuous Integration

#182 Changing the Ship Boost and Planet Speed
  Assets/Scenes/Main scene.unity
  Assets/Scripts/Planets/PlanetRotate.cs
  Assets/Scripts/Ship Movement/ShipMovement.cs
Labels: enhancement

#180 Planet Saved States
  Assets/Prefabs/Animal - Neutral.prefab
  Assets/Prefabs/Animal - Neutral.prefab.meta
  Assets/Prefabs/Planet.prefab
  Assets/Scenes/Main scene.unity
  Assets/Scenes/Planet.unity
  Assets/Scripts/Animals/AnimalController.cs
  Assets/Scripts/Black Hole/BHWarning.cs
  Assets/Scripts/HudBehaviour.cs
  Assets/Scripts/Managers/GameEndManager.cs
  Assets/Scripts/Managers/ScoreManager.cs
  Assets/Scripts/Managers/SpawningManager.cs
  Assets/Scripts/Planets/FindingPlanets.cs
  Assets/Scripts/Planets/PlanetDetection.cs
  Assets/Scripts/Planets/PlanetInfo.cs
  Assets/Scripts/Planets/PlanetInfo.cs.meta
  Assets/Scripts/Planets/PlanetSpawn.cs
  Assets/Scripts/Shared/PlanetStates.cs
  Assets/Scripts/Shared/PlanetStates.cs.meta
  Assets/Scripts/Ship Movement/SpeedEffect.cs
  Assets/Tests/Editor/SpawningManagerTests.cs
  Assets/Tests/Editor/SpawningManagerTests.cs.meta
Labels: enhancement

#186 Planet UI
  Assets/Fonts/Nikea-4BVjK SDF.asset
  Assets/Scenes/Planet.unity
  Assets/Scripts/Animals/AnimalController.cs
  Assets/Scripts/PlanetAnimalCountTEMP.cs
  Assets/Scripts/PlanetAnimalCountTEMP.cs.meta
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Anton SDF.asset
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Bangers SDF.asset
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Electronic Highway Sign SDF.asset
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Oswald Bold SDF.asset
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Roboto-Bold SDF.asset
  Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
Labels: enhancement, help wanted

#178 1.9 Readme update
  README.md
Labels: documentation

#167 V1.9.0
  .github/ISSUE_TEMPLATE/new_feature.md
  .github/PULL_REQUEST_TEMPLATE/basic_template.md
  .github/workflows/ci-build-and-release.yml
  .github/workflows/ci-schedule-cache.yml
  Assets/Fonts/Nikea-4BVjK SDF.asset
  Assets/Prefabs/Animal - Neutral.prefab
  Assets/Prefabs/Animal - Neutral.prefab.meta
  Assets/Prefabs/Planet.prefab
  Assets/Scenes/Game End.unity
  Assets/Scenes/Main scene.unity
  Assets/Scenes/Planet.unity
  Assets/Scenes/Title Screen.unity
  Assets/Scripts/Animals/AnimalController.cs
  Assets/Scripts/Black Hole/BHWarning.cs
  Assets/Scripts/HudBehaviour.cs
  Assets/Scripts/Managers/GameEndManager.cs
  Assets/Scripts/Managers/ScoreManager.cs
  Assets/Scripts/Managers/SpawningManager.cs
  Assets/Scripts/PlanetAnimalCountTEMP.cs
  Assets/Scripts/PlanetAnimalCountTEMP.cs.meta
  Assets/Scripts/Planets/FindingPlanets.cs
  Assets/Scripts/Planets/PlanetDetection.cs
  Assets/Scripts/Planets/PlanetInfo.cs
  Assets/Scripts/Planets/PlanetInfo.cs.meta
  Assets/Scripts/Planets/PlanetRotate.cs
  Assets/Scripts/Planets/PlanetSpawn.cs
  Assets/Scripts/Shared/PlanetStates.cs
  Assets/Scripts/Shared/PlanetStates.cs.meta
  Assets/Scripts/Ship Movement/ShipMovement.cs
  Assets/Scripts/Ship Movement/SpeedEffect.cs
  Assets/Tests/Editor/SpawningManagerTests.cs
  Assets/Tests/Editor/SpawningManagerTests.cs.meta
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Anton SDF.asset
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Bangers SDF.asset
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Electronic Highway Sign SDF.asset
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Oswald Bold SDF.asset
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Roboto-Bold SDF.asset
  Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
  LICENSE
  README.md
Labels: Major Update

#196 Adding game icon
  Assets/Images/Icons.meta
  Assets/Images/Icons/black-hole 128.png
  Assets/Images/Icons/black-hole 128.png.meta
  Assets/Images/Icons/black-hole 16.png
  Assets/Images/Icons/black-hole 16.png.meta
  Assets/Images/Icons/black-hole 256.png
  Assets/Images/Icons/black-hole 256.png.meta
  Assets/Images/Icons/black-hole 32.png
  Assets/Images/Icons/black-hole 32.png.meta
  Assets/Images/Icons/black-hole 512.png
  Assets/Images/Icons/black-hole 512.png.meta
  Assets/Images/Icons/black-hole 64.png
  Assets/Images/Icons/black-hole 64.png.meta
  ProjectSettings/ProjectSettings.asset
  README.md
Labels: Visuals
