Repository BIT-Studio-3/Space-Rescue, pull requests merged in 2023-10, with the labels that each got.

#199 Hostile animal spawns further from player
  Assets/Scripts/Managers/SpawningManager.cs
Labels: bug

#193 Update README.md
  README.md
Labels: documentation

#212 Fixing Build and Caching workflows
  .github/workflows/ci-build-and-release.yml
  .github/workflows/ci-schedule-cache.yml
Labels: bug, Continuous Integration

#215 Dependabot security scanning
  .github/dependabot.yml
Labels: Security

#211 Better black hole growth
  Assets/Prefabs/Black Hole.prefab
  Assets/Prefabs/PlayerShip.prefab
  Assets/Scenes/BH Growth Main Scene.unity
  Assets/Scenes/BH Growth Main Scene.unity.meta
  Assets/Scripts/Black Hole/BlackHoleGrowth.cs
  Assets/Scripts/Planets/FindingPlanets.cs
  Assets/Scripts/Planets/PlanetDetection.cs
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Roboto-Bold SDF.asset
Labels: enhancement, Visuals

#205 Automated Tests
  .github/workflows/ci-testing.yml
  Assets/Tests/Editor/ShipMovementTest.cs
Labels: QA Features, Continuous Integration

#210 Better gravity
  Assets/Prefabs/Black Hole.prefab
  Assets/Scenes/BH Grav Main.unity
  Assets/Scenes/BH Grav Main.unity.meta
  Assets/Scripts/Black Hole/BlackHoleGravity.cs
Labels: enhancement

#217 Fixing player death State
  Assembly-CSharp.csproj
  Assets/Scripts/Animals/AnimalController.cs
  Assets/Scripts/PlayerMovement.cs
Labels: bug

#219 Security policy
  SECURITY.md
Labels: Security

#213 Update Readme
  README.md
Labels: documentation

#221 More Unit Tests
  Assets/Tests/Editor/EditMode.asmdef
  Assets/Tests/Editor/OnPlanetTests.cs
  Assets/Tests/Editor/OnPlanetTests.cs.meta
  Assets/Tests/Editor/PlanetsTests.cs
  Assets/Tests/Editor/PlanetsTests.cs.meta
  Assets/Tests/Editor/ShipMovementTest.cs
  Assets/Tests/Playmode.meta
  Assets/Tests/Playmode/Playmode.asmdef
  Assets/Tests/Playmode/Playmode.asmdef.meta
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Roboto-Bold SDF.asset
Labels: QA Features
