Repository BIT-Studio-3/Space-Rescue, pull requests merged in 2023-08, with the labels that each got.

#123 Title Screen Rework
  Assets/Fonts/Nikea-4BVjK SDF.asset
  Assets/Fonts/Nikea-4BVjK SDF.asset.meta
  Assets/Fonts/Nikea-4BVjK.otf
  Assets/Fonts/Nikea-4BVjK.otf.meta
  Assets/Images/SpaceBackground.jpg
  Assets/Images/SpaceBackground.jpg.meta
  Assets/Scenes/Controls.unity
  Assets/Scenes/Title Screen.unity
  Assets/Scenes/Title Screen.unity.meta
  Assets/Scripts/Managers/GameMenuManager.cs
  Assets/Scripts/Managers/MenuManager.cs
  Assets/Scripts/Managers/SettingsManager.cs
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Anton SDF.asset
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Bangers SDF.asset
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Electronic Highway Sign SDF.asset
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Oswald Bold SDF.asset
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Roboto-Bold SDF.asset
  Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
  Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF.asset
Labels: enhancement

#121 Reworking keybindings
  Assets/Scenes/Controls.unity
  Assets/Scenes/Title Screen.unity
  Assets/Scripts/AnimalController.cs
  Assets/Scripts/Managers/KeypressManager.cs
  Assets/Scripts/Managers/PlanetManager.cs
  Assets/Scripts/Managers/TutorialManager.cs
  Assets/Scripts/Planets/PlanetDetection.cs
  Assets/Scripts/Shared/Keybinds.cs
  Assets/Scripts/Shared/Keybinds.cs.meta
  Assets/Scripts/ShipMovement.cs
Labels: enhancement

#126 Continuous integration
  .github/workflows/ci-build-and-release.yml
Labels: Continuous Integration

#140 Planets spawning inside black hole / each other
  Assets/Prefabs/Black Hole.prefab
  Assets/Scenes/Main scene.unity
  Assets/Scripts/Black Hole/BlackHoleGravity.cs
  Assets/Scripts/Planets/PlanetRotate.cs
  Assets/Scripts/Planets/PlanetSpawn.cs
Labels: bug, enhancement

#125 Readme update
  README.md
Labels: documentation

#142 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/PULL_REQUEST_TEMPLATE/basic_template.md
  .github/PULL_REQUEST_TEMPLATE/major_version.md
  .github/pull_request_template.md
Labels: documentation

#146 v1.7.1
  .github/workflows/ci-build-and-release.yml
  Assets/Scripts/Managers/PauseMenuManager.cs
Labels: Major Update

#154 New End Screen Menu
  Assets/Fonts/Nikea-4BVjK SDF.asset
  Assets/Scenes/Game End.unity
  Assets/Scripts/Managers/GameEndManager.cs
  Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF.asset
  Report.json
Labels: Visuals

#157 fixing the menu resolutions
  Assets/Scenes/Main scene.unity
  Assets/Scenes/New End Screen.unity
  Assets/Scenes/New End Screen.unity.meta
  Assets/Scenes/Planet.unity
  Assets/Scenes/Settings.unity
  Assets/Scenes/Title Screen.unity
Labels: Visuals

#158 Scared + hostile animal
  Assets/ConeCollider.meta
  Assets/ConeCollider/Resources.meta
  Assets/ConeCollider/Resources/Image.meta
  Assets/ConeCollider/Resources/Image/Materials.meta
  Assets/ConeCollider/Resources/Image/Materials/ConeOlliderIcon.mat
  Assets/ConeCollider/Resources/Image/Materials/ConeOlliderIcon.mat.meta
  Assets/ConeCollider/Resources/Image/Materials/circle.mat
  Assets/ConeCollider/Resources/Image/Materials/circle.mat.meta
  Assets/ConeCollider/Resources/Image/Triangle.png
  Assets/ConeCollider/Resources/Image/Triangle.png.meta
  Assets/ConeCollider/Resources/Image/circle.png
  Assets/ConeCollider/Resources/Image/circle.png.meta
  Assets/ConeCollider/Resources/Model.meta
  Assets/ConeCollider/Resources/Model/ConeCollider.fbx
  Assets/ConeCollider/Resources/Model/ConeCollider.fbx.meta
  Assets/ConeCollider/Resources/Model/Materials.meta
  Assets/ConeCollider/Resources/Model/Materials/unnamed.mat
  Assets/ConeCollider/Resources/Model/Materials/unnamed.mat.meta
  Assets/ConeCollider/Resources/Prefab.meta
  Assets/ConeCollider/Resources/Prefab/ConeCollider.prefab
  Assets/ConeCollider/Resources/Prefab/ConeCollider.prefab.meta
  Assets/ConeCollider/Script.meta
  Assets/ConeCollider/Script/ConeCollider.cs
  Assets/ConeCollider/Script/ConeCollider.cs.meta
  Assets/ConeCollider/readme_en.txt
  Assets/ConeCollider/readme_en.txt.meta
  Assets/Prefabs/Animal - Hostile.prefab
  Assets/Prefabs/Animal - Scared.prefab
  Assets/Prefabs/Animal - Scared.prefab.meta
  Assets/Prefabs/FoV.prefab
  Assets/Prefabs/FoV.prefab.meta
  Assets/Scenes/Planet.unity
  Assets/Scripts/Animals/AnimalController.cs
  Assets/Scripts/Animals/Hostile.cs
  Assets/Scripts/Animals/Hostile.cs.meta
  Assets/Scripts/Animals/HostileDetection.cs
  Assets/Scripts/Animals/Scared.cs
  Assets/Scripts/Animals/Scared.cs.meta
  Assets/Scripts/Managers/PlanetManager.cs
  Assets/Scripts/Managers/SpawningManager.cs
Labels: enhancement

#153 Fixing Planet Manager Error
  Assets/Scenes/Main scene.unity
  Assets/Scripts/Managers/PauseMenuManager.cs
  Assets/Scripts/Planets/PlanetDetection.cs
  Assets/Scripts/Planets/PlanetTextureGenerator.cs
Labels: bug

#136 UTF Testing
  Assets/Scripts/Managers/PlanetManager.cs
  Assets/Tests.meta
  Assets/Tests/Editor.meta
  Assets/Tests/Editor/EditMode.asmdef
  Assets/Tests/Editor/EditMode.asmdef.meta
  Assets/Tests/Editor/ShipMovementTest.cs
  Assets/Tests/Editor/ShipMovementTest.cs.meta
  Assets/UTF.meta
Labels: QA Features

#159 Code Validation and Fix Versioning
  .editorconfig
  .github/workflows/ci-build-and-release.yml
  .github/workflows/ci-check-and-format-whitespace.yml
  Assembly-CSharp.csproj
  Space-Rescue.sln
Labels: Continuous Integration
